sonar.projectKey=anzagood1_SoftwIng2WorkShop    
sonar.organization=anzagood1

# Set to the directory containing your code
sonar.sources=workshop

# Encoding
sonar.sourceEncoding=UTF-8

# Satisfies Sonar's Java analyzer requirement when no build system is used
sonar.java.binaries=workshop